"""Add followewers

Revision ID: 306b60a69f3e
Revises: 0c567b70b62a
Create Date: 2020-01-28 11:14:00.274082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '306b60a69f3e'
down_revision = '0c567b70b62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
